[package]
edition = "2024"
name = "jartis-pico"
version = "0.1.0"
build = "build.rs"

crate-type = "bin"

[dependencies]
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }

embedded-hal = { workspace = true }
embedded-hal-nb = { workspace = true }

# Shared with jartis so we can use pins and such
rp-pico = { workspace = true }
rp-pico-w = { workspace = true }

jartis = { path = "../jartis" }

# For unit conversions
fugit = { workspace = true }
heapless = { workspace = true }

# CYW43 Wireless Functionality
# rp-pac = { version = "7.0.0", features = ["rp2040", "rt"], optional = true }
embassy-embedded-hal = { version = "0.3.0",  features = ["defmt"], optional = true }
embassy-sync = { version = "0.7.0", features = ["defmt"], optional = true }
embassy-executor = { version = "0.7.0", features = ["arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "task-arena-size-32768"], optional = true }
# Disable the "rt" feature to let cortex-m-rt populate the INTERRUPTS symbol
embassy-rp = { version = "0.4.0", features = ["defmt", "unstable-pac", "rp2040"], default-features = false, optional = true }
embassy-usb = { version = "0.4.0", features = ["defmt"], optional = true }
embassy-net = { version = "0.7.0", features = ["defmt", "icmp", "tcp", "udp", "raw", "dhcpv4", "medium-ethernet", "dns", "proto-ipv4", "proto-ipv6", "multicast"], optional = true }
embassy-net-wiznet = { version = "0.2.0", features = ["defmt"], optional = true }
embassy-futures = { version = "0.1.0", optional = true }
embassy-time = { version = "0.4.0",  features = ["defmt", "defmt-timestamp-uptime"], optional = true }
embassy-time-driver = { version = "0.2.0", features = ["tick-hz-12_000_000"], optional = true } # Matching rp-pico system MHz
embassy-time-queue-utils = { version = "0.1.0", optional = true }
embassy-usb-logger = { version = "0.4.0", optional = true }
cyw43 = { version = "0.3.0", features = ["defmt", "firmware-logs"], optional = true }
cyw43-pio = { version = "0.4.0", features = ["defmt"], optional = true }
static_cell = { version = "2.1", optional = true }
critical-section = { workspace = true, optional = true }

# Logging
defmt = { workspace = true }
defmt-rtt = { workspace = true }
panic-probe = { workspace = true }
pio = "0.3.0"

[build-dependencies]
bindgen = "0.71.0"

[features]
default = ["wireless"]
rfid_flasher = []
wireless = [
  # "dep:rp-pac",
  # "dep:embassy-embedded-hal",
  "dep:embassy-executor",
  "dep:embassy-futures",
  "dep:embassy-rp",
  "dep:embassy-sync",
  "dep:embassy-time",
  "dep:embassy-time-driver",
  "dep:embassy-time-queue-utils",
  # "dep:embassy-usb",
  # "dep:embassy-net",
  # "dep:embassy-net-wiznet",
  # "dep:embassy-usb-logger",
  "dep:cyw43",
  # "dep:cyw43-pio", # Causing interrupt symbol failures as it imports embassy-rp with the "rt" feature enabled
  "dep:static_cell",
  "dep:critical-section",
]
embassy-time-driver = ["dep:embassy-time-driver"]

# cargo build/run
[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = 3
overflow-checks = true

# cargo build/run --release
[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 3
overflow-checks = false

# do not optimize proc-macro crates = faster builds from scratch
[profile.dev.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false

[profile.release.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false

# cargo test
[profile.test]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = 3
overflow-checks = true

# cargo test --release
[profile.bench]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 3

