[package]
name = "jartis"
version = "0.1.0"
edition = "2024"

crate-type = "lib"

[dependencies]
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }

embedded-hal = { version = "1.0.0" }
embedded-hal-nb = { version = "1.0.0" }

defmt = { workspace = true }
defmt-rtt = { workspace = true }
panic-probe = { workspace = true }

# We're using a Pico by default on this template
rp-pico = { workspace = true }

# For unit conversions
fugit = { workspace = true }
heapless = { workspace = true }

# For mathematics
libm = "0.2.8"

# For OLED display
embedded-graphics = "0.8.1"
ssd1306 = "0.8.4"

# CYW43 Wireless Functionality
critical-section = { workspace = true }
portable-atomic = { version = "1.5", features = ["critical-section"] }

